### ISSUE TITLE
Validar campos ao realizar novo cadastro de animal.

### ISSUE THREAD

**Issue by vanessasoutoc** [scooby-doo-cade-voce/backend#22]
Abaixo temos um exemplo de JSON para cadastro de um novo animal, os comentários no JSON determinam se o campo é obrigatório ou não.

```
{
    "name": "Bob", // obrigatório
    "description": "Um animalzinho feliz.",
    "size_id": 1, // obrigatório
    "specie_id": 1, // obrigatório
    "color_id": 1, // obrigatório
    "responsible_id": 1, // obrigatório
    "medias": [ // obrigatório pelo menos 1 imagem
        {
            "url": "cloud.google.com/cadevc/animals/adsfsq123wr213.png",
            "mediaType": "image/png",
            "animalId": 1
        }
    ]
}
```

**Comment by ylyra** [comment]
O animal pode ser cadastrado pela pessoa que achou, não? (caso, sim, é bem provável que não ele não saiba o nome)

**Comment by vanessasoutoc** [comment]
> O animal pode ser cadastrado pela pessoa que achou, não? (caso, sim, é bem provável que não ele não saiba o nome)

Pode sim, por isso precisamos da validação de cada campo obrigatório.
Hoje a api retorna um erro caso não mande um dos campos obrigatórios, exemplo: name. No entanto esse erro é um erro genérico do DB... precisamos que esse erro seja uma mensagem que pode ser exibida ao usuário (em português) e simples entendimento.

**Comment by JoaoVitorJJV** [comment]
O parâmetro "animalId", do "media" é obrigatório? Como uma pessoa pode enviar o id se o animal ainda não existe na base?


```
{
    "name": "Bob", // obrigatório
    "description": "Um animalzinho feliz.",
    "size_id": 1, // obrigatório
    "specie_id": 1, // obrigatório
    "color_id": 1, // obrigatório
    "responsible_id": 1, // obrigatório
    "medias": [ // obrigatório pelo menos 1 imagem
        {
            "url": "cloud.google.com/cadevc/animals/adsfsq123wr213.png",
            "mediaType": "image/png",
            "animalId": 1
        }
    ]
}
```
