### ISSUE TITLE
Dados do responsável no retorno da listagem / filtro

### ISSUE THREAD

**Issue by vanessasoutoc** [scooby-doo-cade-voce/backend#23]
Nos endpoint que retornamos dados de animais (listagem, busca / filtros, busca por id) devemos retornar os dados do responsável:
nome, telefone (celular) e email.

**Comment by brenorr** [comment]
Será necessário adicionar uma coluna `isTutor`para a tabela responsible ? 

pergunto isso na ideia de retornar algo como:

```json
{
    ...dadosAnimal,
    responsavel: {...}, #dados do responsavel que encontrou no abrigo,
    tutor: {} #Vem da tabela responsible porém esse é o tutor dele.
}
```` 

Faz sentido ter isso também ?

**Comment by vanessasoutoc** [comment]
> Será necessário adicionar uma coluna `isTutor`para a tabela responsible ?
> 
> pergunto isso na ideia de retornar algo como:
> 
> ```json
> {
>     ...dadosAnimal,
>     responsavel: {...}, #dados do responsavel que encontrou no abrigo,
>     tutor: {} #Vem da tabela responsible porém esse é o tutor dele.
> }
> ```
> 
> Faz sentido ter isso também ?

Não, apenas
```json
 {
     ...dadosAnimal,
     responsavel: {...},
 }
 ```
 
 Pra identificar se o responsavel é o dono do animal teremos outro campo dentro de responsavel!

**Comment by brenorr** [comment]
Show ! Vou seguir no desenvolvimento assim.

**Comment by brenorr** [comment]
Uma outra dúvida, atualmente o relacionamento de responsible e animals está OneToOne, devemos manter isso, ou teremos OneToMany ? (1 responsável poderá possuir varios animais) ?

@vanessasoutoc

**Comment by vanessasoutoc** [comment]
> Uma outra dúvida, atualmente o relacionamento de responsible e animals está OneToOne, devemos manter isso, ou teremos OneToMany ? (1 responsável poderá possuir varios animais) ?
> 
> @vanessasoutoc

Esse será mantido por enquanto!

**Comment by brenorr** [comment]
Fechado vou manter OneToOne. 

O cadastro de animal hoje, espera receber apenas o Id do responsável.  Se iremos manter OneToOne, vale receber no cadastro os dados do responsável ìgual realizamos com media ?? 

assim poderemos manter algo como:

```json
{
    "name": "Bob",
    "description": "Um animalzinho feliz.",
    "size_id": 1,
    "specie_id": 1,
    "color_id": 1,
    "age": 9,
    "responsible": {
        "name": "...",
        ....
    },
    "medias": [
        {
            "mediaType": "image/jpg",
            "url": "https://gcloud.com/teste/image.jpg"
        },
        {
            "mediaType": "image/jpg",
            "url": "https://gcloud.com/teste/image.png"
        }
    ]
}
```

Se fizer sentido, posso atuar ja na task que estou

**Comment by vanessasoutoc** [comment]
> Fechado vou manter OneToOne.
> 
> O cadastro de animal hoje, espera receber apenas o Id do responsável. Se iremos manter OneToOne, vale receber no cadastro os dados do responsável ìgual realizamos com media ??
> 
> assim poderemos manter algo como:
> 
> ```json
> {
>     "name": "Bob",
>     "description": "Um animalzinho feliz.",
>     "size_id": 1,
>     "specie_id": 1,
>     "color_id": 1,
>     "age": 9,
>     "responsible": {
>         "name": "...",
>         ....
>     },
>     "medias": [
>         {
>             "mediaType": "image/jpg",
>             "url": "https://gcloud.com/teste/image.jpg"
>         },
>         {
>             "mediaType": "image/jpg",
>             "url": "https://gcloud.com/teste/image.png"
>         }
>     ]
> }
> ```
> 
> Se fizer sentido, posso atuar ja na task que estou

Eu acredito que valeu tá Breno! Assim concentramos tudo em um endpoint apenas!!
Pro front-end é lindo!

**Comment by brenorr** [comment]
Fechado, vou seguindo nesse caminho.
