### ISSUE TITLE
Adicionar relacionamento animal x size

### ISSUE THREAD

**Issue by vanessasoutoc** [scooby-doo-cade-voce/backend#4]
Cada animal tem um tamanho (size_id). Adicionar o relacionamento de animal com sizes.json (lista de tamanhos).

**Comment by JoaoVitorJJV** [comment]
A coluna size_id não tem na entidade do Animal. Precisaria criar ou vocês tem outra idéia? Assim como nenhuma das outras colunas que farão relacionamento.

O que eu estou em mente seria:
Criar uma tabela chamada: animal_size, com as colunas do JSON e fazer o relacionamento

**Comment by vanessasoutoc** [comment]
@JoaoVitorJJV 
Essa atividade engloba apenas a criação do relacionamento, não há necessidade de criar uma tabela para gravar os tamanhos... temos apenas 3 tamanhos de animais, PEQUENO, MÉDIO E GRANDE!
Para o relacionamento precisamos da coluna size_id em Animal, apenas.

**Comment by H4ndrycx** [comment]
> [@JoaoVitorJJV](https://github.com/JoaoVitorJJV) Essa atividade engloba apenas a criação do relacionamento, não há necessidade de criar uma tabela para gravar os tamalhos... temos apenas 3 tamanhos de animais, PEQUENO, MÉDIO E GRANDE! Para o relacionamento precisamos da coluna size_id em Animal, apenas.

Estamos usando o postgres correto? não poderiamos ter isso direto no database, ao invés de uma size_id e uma relação com json externo para dentro do postgres, não seria mais fácil criar apenas um type enum? 

`        CREATE TYPE size_options AS ENUM (
            'Pequeno',
            'Médio',
            'Grande'
        );
`

iriamos manter tudo em nivel de banco de dados com um simple enum, visto que realmente não faz sentido criar uma nova tabela só para 3 rows que não vai mudar.

**Comment by JoaoVitorJJV** [comment]
Sim estou fazendo essa maneira. Estou colocando as novas colunas e gerando as migrations para depois configurar o enum.

**Comment by H4ndrycx** [comment]
@JoaoVitorJJV 

Top acho que é o melhor aproach para esse caso, vi que tem outra issue de espécies também acho que seria bom colocarmos em tabelas e manter tudo no postgres, acho mais simples fazer um `Inner Join` do que parsear `json` oque acha?

ai esses dados podemos colocar um seed para gerar algo pronto, e montar alguma coisinha simples para termos um crudzinho dessas coisas

**Comment by vanessasoutoc** [comment]
@JoaoVitorJJV @H4ndrycx se optarem por usar tabelas e não JSON se atentem para ter um seed para popular as tabelas com os mesmos dados que tem nos JSONs.

**Comment by JoaoVitorJJV** [comment]
A PR foi feita.
